# Generated by Django 4.2.3 on 2023-09-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databanks',
            old_name='banco',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='databanks',
            old_name='descripcion',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='databanks',
            old_name='abonos',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='databanks',
            old_name='fecha',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='databanks',
            old_name='numero_documento',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='databanks',
            old_name='tipo_transaccion',
            new_name='type_expenses',
        ),
        migrations.RemoveField(
            model_name='databanks',
            name='cargos',
        ),
        migrations.RemoveField(
            model_name='databanks',
            name='saldo',
        ),
        migrations.AddField(
            model_name='databanks',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
