# Generated by Django 4.2.3 on 2023-09-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_rename_banco_databanks_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databanks',
            name='category_description',
            field=models.TextField(default=None, null=True),
        ),
    ]
