# Generated by Django 4.2.3 on 2023-09-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_savingtarget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingtarget',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='savingtarget',
            name='user',
        ),
    ]
