# Generated by Django 4.2.3 on 2023-10-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_remove_savingtarget_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Descripción', models.CharField(max_length=255)),
                ('Cuenta', models.CharField(max_length=255)),
                ('Moneda', models.CharField(max_length=50)),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Tipo', models.CharField(max_length=50)),
                ('SubCategoría', models.CharField(max_length=50)),
                ('TipoUsuario', models.CharField(max_length=50)),
                ('SubCategoriaUsuario', models.CharField(max_length=50)),
            ],
        ),
    ]
